[package]
name = "ast-segmenter"
version = "0.2.0-beta.1"
authors = ["Maxwell Huang-Hobbs <mhuan13@gmail.com>"]
license = "Apache-2.0"
description = """
Parses web source files into independent segments
"""
edition = "2018"

[lib]
crate-type = ["lib"]

[dependencies]
ahashmap = { version = "0.2.0", path = "../ahashmap" }
compact_str = "0.9.0"
logger_srcfile = { version = "0.2.0", path = "../logger_srcfile" }
oxc_ast.workspace = true
oxc_ast_visit.workspace = true
oxc_semantic.workspace = true
oxc_span.workspace = true
oxc_utils_parse = { version = "0.1.0", path = "../oxc_utils_parse" }
thiserror.workspace = true


[dev-dependencies]
logger = { version = "0.2.0", path = "../logger" }
oxc_allocator.workspace = true
oxc_parser.workspace = true
