[workspace]
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.75"
path-clean = "0.1.0"
path-slash = "0.2.1"
relative-path = "1.7.2"
regex = "1"
glob = "0.3.0"
rayon = "1.5.1"
thiserror = "1.0.52"
jwalk = "0.5"
serde = { version = "1.0.117", features = ["rc"] }
serde_json = "1.0.59"
napi = { version = "2.16.6", default-features = false, features = ["napi4"] }
napi-derive = "2.16.9"
