[package]
name = "good-fences-rs-core"
version = "0.2.0"
authors = ["Maxwell Huang-Hobbs <mhuan13@gmail.com>"]
edition = "2018"

[dependencies]
jwalk = "0.5"
regex = "1.4.2"
lazy_static = "1.4.0"
serde_derive = "1.0.117"
serde_bytes = "0.11.5"
serde = { version = "1.0.117", features = ["rc"]}
serde_json = "1.0.59"
void = "1.0.2"
relative-path = "1.7.2"
glob = "0.3.0"
pathdiff = "0.2.0"
text-diff = "0.4.0"
rayon = "1.5.0"
path-slash = "0.2.1"
hyperfine = "1.11.0"
swc_ecma_parser = {version = "0.117.0", features = ["typescript"]}
swc_common = {version = "0.27.0", features = ["tty-emitter"]}
swc = "0.215.0"
swc_ecma_ast = "0.94.1"
swc_atoms = "0.4.3"
swc_ecma_visit = "0.76.6"
swc_ecmascript = {version = "0.190.0", features = ["transforms", "visit"]}
swc_plugin = "0.89.1"
swc_core = { version = "0.7.*", features = ["plugin_transform", "transforms"] }
swc_ecma_loader = "0.39.*"
path-clean = "0.1.0"
clap = { version = "3.2.21", features = ["derive"] }
