[workspace]
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.75"
path-clean = "0.1.0"
path-slash = "0.2.1"
relative-path = "1.7.2"
regex = "1"
glob = "0.3.0"
rayon = "1.5.1"
thiserror = "1.0.52"
jwalk = "0.5"
