[package]
name = "good-fences-rs-core"
version = "0.2.0"
authors = ["Maxwell Huang-Hobbs <mhuan13@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
jwalk = "0.5"
lazy_static = "1.4.0"
serde_derive = "1.0.117"
serde_bytes = "0.11.5"
serde = { version = "1.0.117", features = ["rc"]}
serde_json = "1.0.59"
void = "1.0.2"
regex = "1"
relative-path = "1.7.2"
glob = "0.3.0"
pathdiff = "0.2.0"
text-diff = "0.4.0"
rayon = "1.5.0"
path-slash = "0.2.1"
path-clean = "0.1.0"
swc_core = { version = "0.79.70", features = ["ecma_plugin_transform", "ecma_loader_node", "swc_node_base"] }
napi = { version = "2.13.0", default-features = false, features = ["napi4"] }
napi-derive = "2.13.0"
swc_ecma_parser = "0.137.15"

[build-dependencies]
napi-build = "2.0.1"
