/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function goodFences(paths: Array<string>, project: string, baseUrl: string | undefined | null, root: string, output?: string | undefined | null): void
