[package]
name = "js_err"
version = "0.2.0"
authors = ["Maxwell Huang-Hobbs <mhuan13@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib"]

[dependencies]
napi = { version = "2.16.6", default-features = false, features = ["napi4"] }

[build-dependencies]
napi-build = "2.0.1"
