[package]
name = "path_utils"
version = "0.2.0"
authors = ["Maxwell Huang-Hobbs <mhuan13@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = { workspace = true }
relative-path = { workspace = true }
path-slash = { workspace = true }
