[package]
name = "multi_err"
version = "0.2.0"
authors = ["Maxwell Huang-Hobbs <mhuan13@gmail.com>"]
edition = "2018"
description = "A library for handling multiple errors"

[lib]
crate-type = ["lib"]

[dependencies]
anyhow.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
