[package]
name = "logger_srcfile"
version = "0.2.0"
authors = ["Maxwell Huang-Hobbs <mhuan13@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib"]

[dependencies]
logger = { path = "../logger" }
swc_common.workspace = true
