[package]
name = "source_graph"
version = "0.2.0"
authors = ["Maxwell Huang-Hobbs <mhuan13@gmail.com>"]
edition = "2021"
description = "Segment-level import graph for unused detection"

[lib]
crate-type = ["lib"]

[dependencies]
ahashmap = { version = "0.2.0", path = "../ahashmap" }
ast-segmenter = { version = "0.2.0-beta.1", path = "../ast_segmenter" }
compact_str = "0.9.0"

[dev-dependencies]
pretty_assertions.workspace = true
oxc_span.workspace = true
