[package]
name = "import_resolver"
version = "0.2.0"
authors = ["Maxwell Huang-Hobbs <mhuan13@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib"]

[dependencies]
serde_derive = "1.0.117"
serde_bytes = "0.11.5"
serde.workspace = true
serde_json.workspace = true
glob = "0.3.0"
swc_core = { version = "0.83.32", features = [
    "ecma_plugin_transform",
    "ecma_loader_node",
    "ecma_loader_tsc",
    "swc_node_base",
    "ecma_loader_lru",
    "ecma_loader_parking_lot",
] }
swc_ecma_parser = "0.140.0"
swc_ecma_loader = "0.44.5"
anyhow = { workspace = true }
thiserror.workspace = true
path_utils = { path = "../path_utils" }
tsconfig_paths = { path = "../tsconfig_paths" }
path-clean = { workspace = true }
path-slash = { workspace = true }
relative-path = { workspace = true }
lazy_static = "1.4.0"
