use std::path::Path;
use std::path::PathBuf;

use logger::StdioLogger;
use logger_srcfile::WrapFileLogger;
use oxc_allocator::Allocator;
use oxc_semantic::SemanticBuilder;

use ast_segmenter::segment_info::Segment;

#[derive(Debug, thiserror::Error)]
pub enum SourceFileParseError {
    #[error("Auto-generated file")]
    AutogeneratedFile,
    #[error("Unable to load {0} file: {1}")]
    LoadFile(PathBuf, std::io::Error),
    #[error("TypeScript syntax error in {0}: {1}")]
    TypeScriptSyntax(PathBuf, String),
    #[error("Parser error in {0}: {1}")]
    Parser(PathBuf, String),
}

/// Parses a source file and returns per-statement segments via `ast_segmenter::segment_file`.
pub fn get_file_segments(
    file_path: &Path,
) -> Result<Vec<Segment>, SourceFileParseError> {
    let source = match std::fs::read_to_string(file_path) {
        Ok(s) => s,
        Err(e) => return Err(SourceFileParseError::LoadFile(file_path.to_path_buf(), e)),
    };

    if source.contains("// This file is auto-generated") {
        return Err(SourceFileParseError::AutogeneratedFile);
    }

    let allocator = Allocator::default();
    let ret = oxc_utils_parse::parse_file(&allocator, &source, file_path);

    if ret.panicked || !ret.errors.is_empty() {
        let msgs = ret
            .errors
            .iter()
            .map(|e| e.to_string())
            .collect::<Vec<_>>()
            .join("\n");
        return Err(SourceFileParseError::TypeScriptSyntax(
            file_path.to_path_buf(),
            msgs,
        ));
    }

    let semantic = SemanticBuilder::new().build(&ret.program).semantic;
    let stdio_logger = StdioLogger::new();
    let filename = file_path.to_string_lossy();
    // Clone source so it can be owned by the logger while `ret` still borrows it.
    let logger = WrapFileLogger::new(filename, source.clone(), &stdio_logger);

    Ok(ast_segmenter::segment_file(&logger, &ret.program, &semantic))
}
