use std::path::Path;
use std::path::PathBuf;

use logger::StdioLogger;
use logger_srcfile::WrapFileLogger;
use swc_common::comments::SingleThreadedComments;
use swc_common::errors::Handler;
use swc_common::sync::Lrc;
use swc_common::{Globals, Mark, SourceMap, GLOBALS};
use swc_ecma_parser::{Capturing, Parser};
use swc_ecma_transforms::resolver;
use swc_ecma_visit::Fold;

use swc_utils_parse::create_lexer;

use ast_segmenter::segment_info::Segment;

#[derive(Debug, thiserror::Error)]
pub enum SourceFileParseError {
    #[error("Auto-generated file")]
    AutogeneratedFile,
    #[error("Unable to load {0} file: {1}")]
    LoadFile(PathBuf, std::io::Error),
    #[error("TypeScript syntax error in {0}: {1}")]
    TypeScriptSyntax(PathBuf, String),
    #[error("Parser error in {0}: {1}")]
    Parser(PathBuf, String),
}

/// Parses a source file and returns per-statement segments via `ast_segmenter::segment_file`.
pub fn get_file_segments(
    file_path: &Path,
) -> Result<Vec<Segment>, SourceFileParseError> {
    let cm = Lrc::<SourceMap>::default();
    let fm = match cm.load_file(file_path) {
        Ok(f) => f,
        Err(e) => return Err(SourceFileParseError::LoadFile(file_path.to_path_buf(), e)),
    };
    if fm.src.contains("// This file is auto-generated") {
        return Err(SourceFileParseError::AutogeneratedFile);
    }

    let dest_vector: Vec<u8> = Vec::new();
    let dst = Box::new(dest_vector);
    let handler = Handler::with_emitter_writer(dst, Some(cm.clone()));
    let comments = SingleThreadedComments::default();
    let lexer = create_lexer(&fm, Some(&comments));
    let capturing = Capturing::new(lexer);

    let mut parser = Parser::new_from(capturing);
    let errors = parser.take_errors();

    if !errors.is_empty() {
        return Err(SourceFileParseError::Parser(
            file_path.to_path_buf(),
            parser
                .take_errors()
                .into_iter()
                .map(|x| x.into_diagnostic(&handler).message())
                .collect::<Vec<_>>()
                .join("\n"),
        ));
    }

    // Parse file as typescript module to find parse errors.
    let ts_module = match parser.parse_typescript_module() {
        Ok(module) => module,
        Err(error) => {
            let mut diagnostic = error.into_diagnostic(&handler);
            // Avoid panic
            diagnostic.cancel();
            return Err(SourceFileParseError::TypeScriptSyntax(
                file_path.to_path_buf(),
                diagnostic.message(),
            ));
        }
    };

    let stdio_logger = StdioLogger::new();
    let logger = WrapFileLogger::new(cm.as_ref(), &stdio_logger);

    let globals = Globals::new();
    let resolved = GLOBALS.set(&globals, || {
        let mut res = resolver(Mark::fresh(Mark::root()), Mark::fresh(Mark::root()), true);
        res.fold_module(ts_module.clone())
    });

    Ok(ast_segmenter::segment_file(&logger, &resolved, &comments))
}
