[package]
name = "good_fences"
version = "0.2.0"
authors = ["Maxwell Huang-Hobbs <mhuan13@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[[bin]]
name = "unused"
path = "src/bin/unused.rs"

[dependencies]
jwalk.workspace = true
lazy_static = "1.4.0"
serde_derive = "1.0.117"
serde_bytes = "0.11.5"
serde = { version = "1.0.117", features = ["rc"] }
serde_json = "1.0.59"
void = "1.0.2"
relative-path = { workspace = true }
regex = { workspace = true }
glob = { workspace = true }
pathdiff = "0.2.0"
text-diff = "0.4.0"
rayon = { workspace = true }
path-slash = "0.2.1"
path-clean = "0.1.0"
swc_core = { version = "0.83.32", features = [
    "ecma_plugin_transform",
    "ecma_loader_node",
    "ecma_loader_tsc",
    "swc_node_base",
    "ecma_loader_lru",
    "ecma_loader_parking_lot",
] }
napi = { version = "2.16.6", default-features = false, features = ["napi4"] }
napi-derive = "2.16.9"
swc_ecma_parser = "0.140.0"
anyhow = { workspace = true }
thiserror.workspace = true
import_resolver = { path = "../import_resolver" }
unused_finder = { path = "../unused_finder" }

[build-dependencies]
napi-build = "2.0.1"
