# This file is copied to ~/.cargo/config.toml in order to
# configure the build environment for the project within the devcontainer,
# without overriding the build environment on other host systems (e.g. when compiling on osx)

[rust]
# enable cranelift codegen -- faster dev builds
codegen-backends = ["cranelift"]

[target.x86_64-unknown-linux-gnu]
linker = "clang" # required for `mold` linker 
rustflags = [
    # use parallel compilation frontend
    "-Z",
    "threads=8",
    # use `mold` linker for faster link times
    # See https://github.com/rui314/mold
    "-C",
    "link-arg=-fuse-ld=/usr/bin/mold",
]
