name: publish artifacts
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  tests:
    uses: Adjective-Object/good-fences-rs-core/.github/workflows/unittest.yml@main
  publish:
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: pull win artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-napi
      - name: pull linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-napi
      - name: pull macos artifacts
        uses: actions/download-artifact@v3
        with:
          name: macos-napi
      - name: pull js files
        uses: actions/download-artifact@v3
        with:
          name: js-files
      - name: display artifacts
        run: ls -R
      - name: install deps
        run: yarn install
      - name: copy artifacts
        run: |
          mkdir artifacts
          cp *.node artifacts
          yarn artifacts
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          # Skipping publish on this step, only to create tags, push to main new version, this command fails given it needs to publish ona package per platform.
          yarn beachball publish -c .beachball.js -y --no-publish 
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}