name: publish artifacts
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    uses: Adjective-Object/good-fences-rs-core/.github/unittest.yml@main
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: pull win artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-napi
      - name: pull linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-napi
      - name: pull macos artifacts
        uses: actions/download-artifact@v3
        with:
          name: macos-napi
      - name: pull js files
        uses: actions/download-artifact@v3
        with:
          name: js-files
      - name: display artifacts
        run: ls -R
      - name: Publish
        run: |
          mkdir artifacts
          cp *.node artifacts
          yarn install
          yarn artifacts
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}