name: publish artifacts
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  tests:
    uses: Adjective-Object/good-fences-rs-core/.github/workflows/unittest.yml@main
  publish:
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: pull win artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-napi
      - name: pull linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-napi
      - name: pull macos artifacts
        uses: actions/download-artifact@v3
        with:
          name: macos-napi
      - name: pull js files
        uses: actions/download-artifact@v3
        with:
          name: js-files
      - name: display artifacts
        run: ls -R
      - name: install deps
        run: yarn install
      - name: copy artifacts
        run: |
          mkdir artifacts
          cp *.node artifacts
          yarn artifacts
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          git config user.email "mhuan13@gmail.com"
          git config user.name "$GITHUB_ACTOR"
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          yarn beachball publish -c .beachball.js -y --token $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.BEACHBALL_PUSH_PAT }}
          GITHUB_ACTOR: autobot
          
