name: run unit tests
on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:
jobs:
  checks:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    name: 'health checks'
    steps:
      - name: check gclib version
        run: ldd --version
      - name: Check out code
        uses: actions/checkout@v4
      - name: cargo fmt --check
        run: cargo fmt --check
      - name: install dependencies
        run: yarn install
      - name: Check changefile
        run: yarn check-changefile
      - uses: actions/checkout@v4
        with:
          components: clippy
      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: -- --all-targets -Dwarnings
      - name: Run cargo-udeps 
        uses: aig787/cargo-udeps-action@v1
        with:
          version: 'latest'
          args: '--all-targets'
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            test: true
          - host: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
            test: false
          - host: ubuntu-20.04
            target: armv7-unknown-linux-gnueabihf
            test: false
          # This is the latest macos that github provides a non-enterprise-tier x86
          # runner for 
          # See: https://github.com/actions/runner-images?tab=readme-ov-file#available-images
          - host: macos-13 
            target: x86_64-apple-darwin
            test: true
          - host: macos-latest
            target: aarch64-apple-darwin
            test: false
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            test: true
          - host: windows-latest
            target: aarch64-pc-windows-msvc
            test: false
    name: ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: napi build
        run: yarn install && yarn build
      - name: run napi tests
        if: ${{ matrix.settings.test }}
        run: yarn test
      - name: cargo test
        if: ${{ matrix.settings.test }}
        run: cargo test --release
      - name: upload-artifacts
        uses: actions/upload-artifact@v3
        if: needs.pr-check.outputs.number != 'null'
        with:
          name: bindings-${{ matrix.settings.target }}
          path: ./*.node
          if-no-files-found: error
      - name: upload js files
        if: needs.pr-check.outputs.number != 'null' && ${{ matrix.settings.target }} == 'linux-x64-gnu'
        uses: actions/upload-artifact@v3
        with:
          name: js-files
          if-no-files-found: error
          path: |
            index.js
            index.d.ts
